//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Course_Regist.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_COURSETYPE                  129
#define IDM_LOGIN                       130
#define IDD_LOGIN                       131
#define IDC_EDIT2                       132
#define IDD_MPassWord                   132
#define IDC_EDIT1                       133
#define IDC_NewPassword                 133
#define IDD_AddStu                      133
#define IDC_ASID                        133
#define IDC_DelStu                      133
#define IDC_ASNM                        134
#define IDD_DelStu                      134
#define IDC_ASID2                       134
#define IDC_GSSC                        134
#define IDC_ASBD                        135
#define IDD_MStu                        135
#define IDC_ASGD                        136
#define IDD_AddPro                      136
#define IDC_ASST                        137
#define IDD_DelPro                      137
#define IDB_NAME                        137
#define IDD_MPro                        138
#define IDB_MM                          138
#define IDC_MStuSC                      139
#define IDD_AddCS                       139
#define IDD_DelCS                       140
#define IDD_MCS                         141
#define IDD_SC                          148
#define IDD_TSC                         148
#define IDD_SSC                         149
#define IDD_Grade                       150
#define IDD_MSCORE                      151
#define IDC_MGetInfo                    1002
#define IDC_MStuID                      1003
#define IDC_MStuNM                      1004
#define IDC_MStuBD                      1005
#define IDC_MStuGD                      1006
#define IDC_NAME                        1007
#define IDC_MStuST                      1007
#define IDC_APID                        1008
#define IDC_APNM                        1009
#define IDC_APBD                        1010
#define IDC_APDP                        1011
#define IDC_APST                        1012
#define IDC_DelPro                      1013
#define IDC_MProSC                      1014
#define IDC_MProID                      1015
#define IDC_MProNM                      1016
#define IDC_MProBD                      1017
#define IDC_MProDP                      1018
#define IDC_PASSWORD                    1019
#define IDC_MProST                      1019
#define IDC_ACSID                       1020
#define IDC_ACSNM                       1021
#define IDC_ACSTY                       1022
#define IDC_DelCS                       1023
#define IDC_MCSSC                       1024
#define IDC_MCSID                       1025
#define IDC_MCSNM                       1026
#define IDC_MCSTY                       1027
#define IDC_CHECK1                      1028
#define IDC_TREE1                       1039
#define IDC_MONTHCALENDAR1              1044
#define IDC_LISTTTS                     1047
#define IDC_LISTTHS                     1048
#define IDC_RADIO1                      1049
#define IDC_LISTTHS2                    1049
#define IDC_LISTMC                      1049
#define IDC_RADIO2                      1050
#define IDC_LISTGH                      1050
#define IDC_TEXCUTE                     1051
#define IDC_SeekCIF                     1052
#define IDC_TSeekCIF                    1052
#define IDC_TSCID                       1053
#define IDC_TSCNM                       1054
#define IDC_TSCT                        1055
#define IDC_TSCTY                       1056
#define IDC_TSSLTED                     1057
#define IDC_BUTTON1                     1058
#define IDC_LoadStu                     1058
#define IDC_BUTTON2                     1059
#define IDC_DENFEN                      1059
#define IDC_LISTSTS                     1060
#define IDC_SSCID                       1061
#define IDC_SSCNM                       1062
#define IDC_SSCT                        1063
#define IDC_SSCTY                       1064
#define IDC_SSSLTED                     1065
#define IDC_SSeekCIF                    1066
#define IDC_SEXCUTE                     1067
#define IDC_LISTSHS                     1068
#define IDC_RADIO3                      1069
#define IDC_RADIO4                      1070
#define IDC_LISTNG                      1071
#define IDC_StuSLB                      1072
#define IDC_StuSLX                      1073
#define IDC_GCurC                       1074
#define IDC_GSID                        1075
#define IDC_CNAME1                      1076
#define IDC_CNAME2                      1077
#define IDC_CNAME3                      1078
#define IDC_CNAME4                      1079
#define IDC_CNAME5                      1080
#define IDC_CNAME6                      1081
#define IDC_CSCORE1                     1082
#define IDC_CSCORE2                     1083
#define IDC_CSCORE3                     1084
#define IDC_CSCORE4                     1085
#define IDC_CSCORE5                     1086
#define IDC_CSCORE6                     1087
#define IDM_INFORMATION                 32774
#define IDM_MPassWord                   32775
#define IDM_AddStu                      32776
#define IDM_LOGOUT                      32777
#define IDM_DelStu                      32778
#define IDM_MStu                        32779
#define IDM_AddPro                      32780
#define IDM_DelPro                      32781
#define IDM_MPro                        32782
#define IDM_AddCS                       32783
#define IDM_DelCS                       32784
#define IDM_MCS                         32785
#define IDM_TSC                         32788
#define IDM_SSC                         32789
#define IDM_GRADE                       32791
#define IDM_MSCORE                      32792
#define IDM_NextStep                    32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
